#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

function packageName() {
  echo $(echo $1 | sed 's/\.\/packages\///')
}

yarn

for packageDir in `find ./packages/* -type d -maxdepth 0`; do
  package=$(packageName $packageDir)
  cd $packageDir
  yarn install
  cd ../..
done
